
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button clear;

	private global::Gtk.Button btn7;

	private global::Gtk.Button btn8;

	private global::Gtk.Button btn9;

	private global::Gtk.Button add;

	private global::Gtk.Label result;

	private global::Gtk.Button btn4;

	private global::Gtk.Button btn5;

	private global::Gtk.Button btn6;

	private global::Gtk.Button expect;

	private global::Gtk.Button btn1;

	private global::Gtk.Button btn2;

	private global::Gtk.Button btn3;

	private global::Gtk.Button mul;

	private global::Gtk.Button btn;

	private global::Gtk.Button dot;

	private global::Gtk.Button equal;

	private global::Gtk.Button button18;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 0;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.clear = new global::Gtk.Button();
		this.clear.WidthRequest = 64;
		this.clear.HeightRequest = 64;
		this.clear.CanFocus = true;
		this.clear.Name = "clear";
		this.clear.UseUnderline = true;
		this.clear.Label = global::Mono.Unix.Catalog.GetString("C");
		this.fixed1.Add(this.clear);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.clear]));
		w1.X = 20;
		w1.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn7 = new global::Gtk.Button();
		this.btn7.WidthRequest = 60;
		this.btn7.HeightRequest = 60;
		this.btn7.CanFocus = true;
		this.btn7.Name = "btn7";
		this.btn7.UseUnderline = true;
		this.btn7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.fixed1.Add(this.btn7);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn7]));
		w2.X = 20;
		w2.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn8 = new global::Gtk.Button();
		this.btn8.WidthRequest = 60;
		this.btn8.HeightRequest = 60;
		this.btn8.CanFocus = true;
		this.btn8.Name = "btn8";
		this.btn8.UseUnderline = true;
		this.btn8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.fixed1.Add(this.btn8);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn8]));
		w3.X = 100;
		w3.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn9 = new global::Gtk.Button();
		this.btn9.WidthRequest = 60;
		this.btn9.HeightRequest = 60;
		this.btn9.CanFocus = true;
		this.btn9.Name = "btn9";
		this.btn9.UseUnderline = true;
		this.btn9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.fixed1.Add(this.btn9);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn9]));
		w4.X = 180;
		w4.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.add = new global::Gtk.Button();
		this.add.WidthRequest = 60;
		this.add.HeightRequest = 60;
		this.add.CanFocus = true;
		this.add.Name = "add";
		this.add.UseUnderline = true;
		this.add.Label = global::Mono.Unix.Catalog.GetString("+");
		this.fixed1.Add(this.add);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.add]));
		w5.X = 260;
		w5.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.result = new global::Gtk.Label();
		this.result.WidthRequest = 300;
		this.result.HeightRequest = 42;
		this.result.Name = "result";
		this.fixed1.Add(this.result);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.result]));
		w6.X = 23;
		w6.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn4 = new global::Gtk.Button();
		this.btn4.WidthRequest = 60;
		this.btn4.HeightRequest = 60;
		this.btn4.CanFocus = true;
		this.btn4.Name = "btn4";
		this.btn4.UseUnderline = true;
		this.btn4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.fixed1.Add(this.btn4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn4]));
		w7.X = 20;
		w7.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn5 = new global::Gtk.Button();
		this.btn5.WidthRequest = 60;
		this.btn5.HeightRequest = 60;
		this.btn5.CanFocus = true;
		this.btn5.Name = "btn5";
		this.btn5.UseUnderline = true;
		this.btn5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.fixed1.Add(this.btn5);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn5]));
		w8.X = 100;
		w8.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn6 = new global::Gtk.Button();
		this.btn6.WidthRequest = 60;
		this.btn6.HeightRequest = 60;
		this.btn6.CanFocus = true;
		this.btn6.Name = "btn6";
		this.btn6.UseUnderline = true;
		this.btn6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.fixed1.Add(this.btn6);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn6]));
		w9.X = 180;
		w9.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.expect = new global::Gtk.Button();
		this.expect.WidthRequest = 60;
		this.expect.HeightRequest = 60;
		this.expect.CanFocus = true;
		this.expect.Name = "expect";
		this.expect.UseUnderline = true;
		this.expect.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.expect);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.expect]));
		w10.X = 260;
		w10.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn1 = new global::Gtk.Button();
		this.btn1.WidthRequest = 60;
		this.btn1.HeightRequest = 60;
		this.btn1.CanFocus = true;
		this.btn1.Name = "btn1";
		this.btn1.UseUnderline = true;
		this.btn1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.fixed1.Add(this.btn1);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn1]));
		w11.X = 20;
		w11.Y = 280;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn2 = new global::Gtk.Button();
		this.btn2.WidthRequest = 60;
		this.btn2.HeightRequest = 60;
		this.btn2.CanFocus = true;
		this.btn2.Name = "btn2";
		this.btn2.UseUnderline = true;
		this.btn2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.fixed1.Add(this.btn2);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn2]));
		w12.X = 100;
		w12.Y = 280;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn3 = new global::Gtk.Button();
		this.btn3.WidthRequest = 60;
		this.btn3.HeightRequest = 60;
		this.btn3.CanFocus = true;
		this.btn3.Name = "btn3";
		this.btn3.UseUnderline = true;
		this.btn3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.fixed1.Add(this.btn3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn3]));
		w13.X = 180;
		w13.Y = 280;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.mul = new global::Gtk.Button();
		this.mul.WidthRequest = 60;
		this.mul.HeightRequest = 60;
		this.mul.CanFocus = true;
		this.mul.Name = "mul";
		this.mul.UseUnderline = true;
		this.mul.Label = global::Mono.Unix.Catalog.GetString("x");
		this.fixed1.Add(this.mul);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.mul]));
		w14.X = 260;
		w14.Y = 280;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn = new global::Gtk.Button();
		this.btn.WidthRequest = 60;
		this.btn.HeightRequest = 60;
		this.btn.CanFocus = true;
		this.btn.Name = "btn";
		this.btn.UseUnderline = true;
		this.btn.Label = global::Mono.Unix.Catalog.GetString("0");
		this.fixed1.Add(this.btn);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn]));
		w15.X = 20;
		w15.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dot = new global::Gtk.Button();
		this.dot.WidthRequest = 60;
		this.dot.HeightRequest = 60;
		this.dot.CanFocus = true;
		this.dot.Name = "dot";
		this.dot.UseUnderline = true;
		this.dot.Label = global::Mono.Unix.Catalog.GetString(".");
		this.fixed1.Add(this.dot);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.dot]));
		w16.X = 100;
		w16.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.equal = new global::Gtk.Button();
		this.equal.WidthRequest = 60;
		this.equal.HeightRequest = 60;
		this.equal.CanFocus = true;
		this.equal.Name = "equal";
		this.equal.UseUnderline = true;
		this.equal.Label = global::Mono.Unix.Catalog.GetString("=");
		this.fixed1.Add(this.equal);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.equal]));
		w17.X = 180;
		w17.Y = 350;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button18 = new global::Gtk.Button();
		this.button18.WidthRequest = 60;
		this.button18.HeightRequest = 60;
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString(":");
		this.fixed1.Add(this.button18);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button18]));
		w18.X = 260;
		w18.Y = 350;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 356;
		this.DefaultHeight = 447;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.clear.Clicked += new global::System.EventHandler(this.onClearClick);
		this.btn7.Clicked += new global::System.EventHandler(this.onClick);
		this.btn8.Clicked += new global::System.EventHandler(this.onClick);
		this.btn9.Clicked += new global::System.EventHandler(this.onClick);
		this.add.Clicked += new global::System.EventHandler(this.onOperatorClick);
		this.btn4.Clicked += new global::System.EventHandler(this.onClick);
		this.btn5.Clicked += new global::System.EventHandler(this.onClick);
		this.btn6.Clicked += new global::System.EventHandler(this.onClick);
		this.expect.Clicked += new global::System.EventHandler(this.onOperatorClick);
		this.btn1.Clicked += new global::System.EventHandler(this.onClick);
		this.btn2.Clicked += new global::System.EventHandler(this.onClick);
		this.btn3.Clicked += new global::System.EventHandler(this.onClick);
		this.mul.Clicked += new global::System.EventHandler(this.onOperatorClick);
		this.btn.Clicked += new global::System.EventHandler(this.onClick);
		this.dot.Clicked += new global::System.EventHandler(this.onDotClick);
		this.equal.Clicked += new global::System.EventHandler(this.onEqualClick);
		this.button18.Clicked += new global::System.EventHandler(this.onOperatorClick);
	}
}
